// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBWnps6FOYP7W33_jNjYTTllokpYP9ilI',
    appId: '1:952623983658:web:d87b1efbe6b7d780c62753',
    messagingSenderId: '952623983658',
    projectId: 'classmanagerapp-37901',
    authDomain: 'classmanagerapp-37901.firebaseapp.com',
    storageBucket: 'classmanagerapp-37901.firebasestorage.app',
    measurementId: 'G-90X4V4Z7QM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIezrzBS2Fb7oLsjmGqhZhN2mDrly8WtE',
    appId: '1:952623983658:android:69ae0b03c8fd541bc62753',
    messagingSenderId: '952623983658',
    projectId: 'classmanagerapp-37901',
    storageBucket: 'classmanagerapp-37901.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5_kzFUep4VeHmCjAQFOqbLlwFMdCJEXc',
    appId: '1:952623983658:ios:5286ea4ed424e46fc62753',
    messagingSenderId: '952623983658',
    projectId: 'classmanagerapp-37901',
    storageBucket: 'classmanagerapp-37901.firebasestorage.app',
    iosBundleId: 'com.example.classmanagerapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5_kzFUep4VeHmCjAQFOqbLlwFMdCJEXc',
    appId: '1:952623983658:ios:5286ea4ed424e46fc62753',
    messagingSenderId: '952623983658',
    projectId: 'classmanagerapp-37901',
    storageBucket: 'classmanagerapp-37901.firebasestorage.app',
    iosBundleId: 'com.example.classmanagerapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBWnps6FOYP7W33_jNjYTTllokpYP9ilI',
    appId: '1:952623983658:web:1d840e71a2963aa4c62753',
    messagingSenderId: '952623983658',
    projectId: 'classmanagerapp-37901',
    authDomain: 'classmanagerapp-37901.firebaseapp.com',
    storageBucket: 'classmanagerapp-37901.firebasestorage.app',
    measurementId: 'G-9QK6VYW3NL',
  );
}
